command = '/home/bookr/Bookr-django-project/venv/bin/gunicorn'
pythonpath = '/home/bookr/Bookr-django-project/bookr/'
bind = '127.0.0.1:8001'
workers = 3
user = 'bookr'
limit_request_fields = 32000
limit_request_field_size = 0
raw_env = 'DJANGO_SETTINGS_MODULE=bookr.settings'
#daemon = True
